### 1. Cleaning Customers Dataset

In [234]:
import pandas as pd

In [235]:
# Load customers dataset
customers_df = pd.read_csv('C:\\Users\\ayesh\\Desktop\\DWH Assignments\\Dataset\\customers.csv')
customers_df

,CustomerID,FullName,Phone,SignupDate,Email
0,CUST7000,Stephanie Galvan,001-346-805-1358x20771,1972/05/31,mbaker@hotmail.com
1,CUST7001,Angel Bowers,209.905.6961,1976.01.27,jenniferbarnes@yahoo.com
2,CUST7002,Daniel Bailey,001-270-679-1923x340,2008.04.25,carolsanchez@owens.org
3,CUST7003,Gary Smith,256.744.5990x596,1997-08-29,ugraham@hotmail.com
4,CUST7004,Michael James,001-680-429-4030,1986/10/07,edwardskevin@medina.com
...,...,...,...,...,...
14995,CUST21995,Jocelyn Carney,250-882-4224x6256,2011-11-03,martinchristina@gmail.com
14996,CUST21996,Kristen Stewart,+1-803-724-6714x2253,1991-02-10,davisandre@vincent.com
14997,CUST21997,William Reese,803.241.9145x893,1987.11.20,kkane@yahoo.com
14998,NaN,Joshua Cook,001-821-331-5321x9038,1993.09.30,xmichael@hotmail.com
14999,CUST21999,Rebecca Newton,001-114-077-1910x9847,1991/10/22,montesdavid@robbins.com

In [236]:
#Checking for missing values
customers_missing = customers_df.isnull().sum()
customers_missing

CustomerID    450
FullName      450
Phone         450
SignupDate    450
Email         450
dtype: int64

In [237]:
#Checking for duplicates
customers_duplicates = customers_df.duplicated().sum()
customers_duplicates

0

In [238]:
#Checking for inconsistencies
def check_inconsistencies(df):
    # Check for missing values
    missing_values = df.isnull().sum()
    
    # Check for duplicate rows
    duplicate_rows = df.duplicated().sum()
    
    # Create a dictionary of inconsistencies
    inconsistencies = {
        "missing_values": missing_values,
        "duplicate_rows": duplicate_rows
    }
    
    return inconsistencies

In [239]:
customers_missing_after = customers_df.isnull().sum()  # Check if missing values are handled
customers_missing_after

CustomerID    450
FullName      450
Phone         450
SignupDate    450
Email         450
dtype: int64

In [240]:
customers_inconsistencies_after = check_inconsistencies(customers_df)  # Check for any remaining inconsistencies
customers_inconsistencies_after

{'missing_values': CustomerID    450
 FullName      450
 Phone         450
 SignupDate    450
 Email         450
 dtype: int64,
 'duplicate_rows': 0}

In [241]:
# Example usage
customers_inconsistencies = check_inconsistencies(customers_df)
print(customers_inconsistencies)

{'missing_values': CustomerID    450
FullName      450
Phone         450
SignupDate    450
Email         450
dtype: int64, 'duplicate_rows': 0}

In [242]:
#Cleaning the dataset
def clean_data(df):
    # Drop rows with missing values
    df_cleaned = df.dropna()

    # Drop duplicate rows
    df_cleaned = df_cleaned.drop_duplicates()

    # Convert column data types if needed (example: convert 'Age' to int)
    # df_cleaned['Age'] = df_cleaned['Age'].astype(int)  # Uncomment and modify as needed

    # Return the cleaned dataframe
    return df_cleaned

In [243]:
customers_data_types_before = customers_df.dtypes
customers_data_types_before

CustomerID    object
FullName      object
Phone         object
SignupDate    object
Email         object
dtype: object

In [244]:
# Correcting data types
customers_df['SignupDate'] = pd.to_datetime(customers_df['SignupDate'], errors='coerce')  # Standardize to datetime
customers_df['CustomerID'] = customers_df['CustomerID'].astype('category')  # Convert CustomerID to category
customers_df['Phone'] = customers_df['Phone'].astype('category')  # Convert Phone to category
customers_df['Email'] = customers_df['Email'].astype('category')  # Convert Email to category

In [245]:
customers_df.dtypes

CustomerID          category
FullName              object
Phone               category
SignupDate    datetime64[ns]
Email               category
dtype: object

In [246]:
# Standardizing date format
customers_df['SignupDate'] = customers_df['SignupDate'].dt.strftime('%Y-%m-%d')

In [247]:
# Step 3: Handle missing values
# For categorical columns, use mode to fill missing values
customers_df['FullName'] = customers_df['FullName'].fillna(customers_df['FullName'].mode()[0])
customers_df['Phone'] = customers_df['Phone'].fillna(customers_df['Phone'].mode()[0])
customers_df['Email'] = customers_df['Email'].fillna(customers_df['Email'].mode()[0])

In [248]:
# For numerical columns, use mean to fill missing values (e.g., customer IDs)
customers_df['CustomerID'] = customers_df['CustomerID'].fillna(customers_df['CustomerID'].mode()[0])

In [249]:
# Step 4: Check for duplicates and remove them
customers_df = customers_df.drop_duplicates()

In [250]:
# Fill missing SignupDate with placeholder date 
customers_cleaned['SignupDate'] = customers_cleaned['SignupDate'].fillna('2023-01-01')

In [251]:
# Step 5: Display the cleaned dataset
customers_df.head()

,CustomerID,FullName,Phone,SignupDate,Email
0,CUST7000,Stephanie Galvan,001-346-805-1358x20771,1972-05-31,mbaker@hotmail.com
1,CUST7001,Angel Bowers,209.905.6961,NaN,jenniferbarnes@yahoo.com
2,CUST7002,Daniel Bailey,001-270-679-1923x340,NaN,carolsanchez@owens.org
3,CUST7003,Gary Smith,256.744.5990x596,NaN,ugraham@hotmail.com
4,CUST7004,Michael James,001-680-429-4030,1986-10-07,edwardskevin@medina.com

In [252]:
# Summary of missing values, duplicates, and inconsistencies
customers_missing, customers_duplicates, customers_inconsistencies

(CustomerID    450
 FullName      450
 Phone         450
 SignupDate    450
 Email         450
 dtype: int64,
 0,
 {'missing_values': CustomerID    450
  FullName      450
  Phone         450
  SignupDate    450
  Email         450
  dtype: int64,
  'duplicate_rows': 0})

### 2. Cleaning Drivers Dataset

In [253]:
# Load drivers dataset
drivers_df = pd.read_csv('C:\\Users\\ayesh\\Desktop\\DWH Assignments\\Dataset\\drivers.csv')
drivers_df

,DriverID,FullName,Phone,LicenseNumber,JoinDate,City
0,DRV1000,Brian Hopkins,+1-817-693-6961,fxeX6dvSXM,2020/12/30,NYC
1,DRV1001,NaN,(421)724-8133,w7T26UTKcP,2016-11-11,Houston
2,DRV1002,Connie Beck,+1-059-067-3834x2715,yW0zeRz5u0,1982.04.12,NYC
3,DRV1003,Kelsey Vega DVM,001-774-288-2351x242,O3zuHdGhi1,1990.01.17,Chi-town
4,DRV1004,Dana Brown,NaN,q6wb1hqhgy,2020/08/15,NYC
...,...,...,...,...,...,...
4995,DRV5995,James Gomez,NaN,kZrWZEPTHO,1999/03/09,NYC
4996,DRV5996,Brian Wilson,NaN,A11eDlvcOu,2023-01-15,Chi-town
4997,DRV5997,Lori Baird,905.037.7045,1DyElVk9sX,2008.05.24,NYC
4998,DRV5998,Jerry Miller,(166)196-3785,xEPLs6adpp,1980.09.13,Los Angeles
4999,DRV5999,Justin Galvan,NaN,4LGpvD9xie,NaN,New York

In [254]:
# Checking for missing values
drivers_missing = drivers_df.isnull().sum()
drivers_missing

DriverID         150
FullName         150
Phone            650
LicenseNumber    660
JoinDate         150
City             150
dtype: int64

In [255]:
# Checking for duplicates
drivers_duplicates = drivers_df.duplicated().sum()
drivers_duplicates

0

In [256]:
# Checking for inconsistencies
drivers_inconsistencies = check_inconsistencies(drivers_df)
drivers_inconsistencies

{'missing_values': DriverID         150
 FullName         150
 Phone            650
 LicenseNumber    660
 JoinDate         150
 City             150
 dtype: int64,
 'duplicate_rows': 0}

In [257]:
drivers_data_types_before = drivers_df.dtypes
drivers_data_types_before

DriverID         object
FullName         object
Phone            object
LicenseNumber    object
JoinDate         object
City             object
dtype: object

In [258]:
drivers_df['JoinDate'] = pd.to_datetime(drivers_df['JoinDate'], errors='coerce')  # Convert JoinDate to datetime
drivers_df['DriverID'] = drivers_df['DriverID'].astype('category')  # Convert DriverID to category
drivers_df['Phone'] = drivers_df['Phone'].astype('category')  # Convert Phone to category
drivers_df['City'] = drivers_df['City'].astype('category')  # Convert City to category

In [259]:
drivers_data_types_after = drivers_df.dtypes
drivers_data_types_after

DriverID               category
FullName                 object
Phone                  category
LicenseNumber            object
JoinDate         datetime64[ns]
City                   category
dtype: object

In [260]:
# missing values
# For categorical columns, im using the mode to fill missing values
drivers_df['FullName'] = drivers_df['FullName'].fillna(drivers_df['FullName'].mode()[0])
drivers_df['Phone'] = drivers_df['Phone'].fillna(drivers_df['Phone'].mode()[0])
drivers_df['City'] = drivers_df['City'].fillna(drivers_df['City'].mode()[0])

In [261]:
# For numerical columns, use the mode to fill missing values (e.g., DriverID)
drivers_df['DriverID'] = drivers_df['DriverID'].fillna(drivers_df['DriverID'].mode()[0])

# Remove duplicates
drivers_df = drivers_df.drop_duplicates()

# Step 6: Check for any remaining missing values
drivers_missing_after = drivers_df.isnull().sum
drivers_missing_after

<bound method DataFrame.sum of       DriverID  FullName  Phone  LicenseNumber  JoinDate   City
0        False     False  False          False     False  False
1        False     False  False          False      True  False
2        False     False  False          False      True  False
3        False     False  False          False      True  False
4        False     False  False          False     False  False
...        ...       ...    ...            ...       ...    ...
4995     False     False  False          False     False  False
4996     False     False  False          False      True  False
4997     False     False  False          False      True  False
4998     False     False  False          False      True  False
4999     False     False  False          False      True  False

[5000 rows x 6 columns]>

In [262]:
# Cleaned dataset's first few rows
drivers_cleaned.head()

,DriverID,FullName,Phone,LicenseNumber,JoinDate,City
0,DRV1000,Brian Hopkins,+1-817-693-6961,fxeX6dvSXM,2020/12/30,NYC
2,DRV1002,Connie Beck,+1-059-067-3834x2715,yW0zeRz5u0,1982.04.12,NYC
3,DRV1003,Kelsey Vega DVM,001-774-288-2351x242,O3zuHdGhi1,1990.01.17,Chi-town
5,DRV1005,Autumn Bryant,(996)928-7884x8613,11DidxDTTV,1978-12-19,Chicago
6,DRV1006,William Davis,465.341.6149,afMFid5B2D,1981/07/11,Chicago

In [263]:
# Summary of missing values, duplicates, and inconsistencies
drivers_data_types_before, drivers_data_types_after, drivers_missing_after, drivers_df.head()

(DriverID         object
 FullName         object
 Phone            object
 LicenseNumber    object
 JoinDate         object
 City             object
 dtype: object,
 DriverID               category
 FullName                 object
 Phone                  category
 LicenseNumber            object
 JoinDate         datetime64[ns]
 City                   category
 dtype: object,
 <bound method DataFrame.sum of       DriverID  FullName  Phone  LicenseNumber  JoinDate   City
 0        False     False  False          False     False  False
 1        False     False  False          False      True  False
 2        False     False  False          False      True  False
 3        False     False  False          False      True  False
 4        False     False  False          False     False  False
 ...        ...       ...    ...            ...       ...    ...
 4995     False     False  False          False     False  False
 4996     False     False  False          False      True  False
 4997     False     False  False          False      True  False
 4998     False     False  False          False      True  False
 4999     False     False  False          False      True  False

 [5000 rows x 6 columns]>,
   DriverID         FullName                 Phone LicenseNumber   JoinDate  \
 0  DRV1000    Brian Hopkins       +1-817-693-6961    fxeX6dvSXM 2020-12-30
 1  DRV1001     Amanda Smith         (421)724-8133    w7T26UTKcP        NaT
 2  DRV1002      Connie Beck  +1-059-067-3834x2715    yW0zeRz5u0        NaT
 3  DRV1003  Kelsey Vega DVM  001-774-288-2351x242    O3zuHdGhi1        NaT
 4  DRV1004       Dana Brown    (000)465-7946x2034    q6wb1hqhgy 2020-08-15

        City
 0       NYC
 1   Houston
 2       NYC
 3  Chi-town
 4       NYC  )

### 3. Cleaning Payments Dataset

In [264]:
# Loading payments dataset
payments_df = pd.read_csv('C:\\Users\\ayesh\\Desktop\\DWH Assignments\\Dataset\\payments.csv')
payments_df

       PaymentID     RideID  Amount    Mode PaymentDate
0      PAYT11000  RIDE50531   98.86    Card  1986-08-04
1      PAYT11001  RIDE71644   36.48    CASH  1998-02-28
2      PAYT11002  RIDE85572   22.12    CASH  1993/04/17
3      PAYT11003  RIDE57011   42.15    CASH  1993-08-31
4      PAYT11004  RIDE80861    8.36    Cash  1979.09.12
...          ...        ...     ...     ...         ...
44995  PAYT55995  RIDE34614   84.11    Card  2022.03.14
44996  PAYT55996  RIDE41212   73.90    Card  1975/07/19
44997  PAYT55997  RIDE53968    6.40  PayPal  2016-12-02
44998  PAYT55998  RIDE48433   64.77    Cash  2003/01/16
44999  PAYT55999  RIDE88881   13.43  PayPal  2014/12/31

[45000 rows x 5 columns]

In [265]:
# Checking for missing values
payments_missing = payments_df.isnull().sum()
payments_missing

PaymentID       900
RideID         2654
Amount          900
Mode            900
PaymentDate     900
dtype: int64

In [266]:
#Handling missing PaymentDate values
payments_df['PaymentDate'] = payments_df['PaymentDate'].fillna('2023-01-01')  # Fill with a placeholder date (or use latest date)
payments_df['PaymentDate']

0        1986-08-04
1        1998-02-28
2        1993/04/17
3        1993-08-31
4        1979.09.12
            ...
44995    2022.03.14
44996    1975/07/19
44997    2016-12-02
44998    2003/01/16
44999    2014/12/31
Name: PaymentDate, Length: 45000, dtype: object

In [267]:
# Checking for duplicates
payments_duplicates = payments_df.duplicated().sum()
payments_duplicates

0

In [268]:
# Checking for inconsistencies
payments_inconsistencies = check_inconsistencies(payments_df)
payments_inconsistencies

{'missing_values': PaymentID       900
 RideID         2654
 Amount          900
 Mode            900
 PaymentDate       0
 dtype: int64,
 'duplicate_rows': 0}

In [269]:
#datatypes
payments_data_types_before = payments_df.dtypes
payments_data_types_before

PaymentID       object
RideID          object
Amount         float64
Mode            object
PaymentDate     object
dtype: object

In [270]:
#fixing
payments_df['PaymentDate'] = pd.to_datetime(payments_df['PaymentDate'], errors='coerce')  # Convert PaymentDate to datetime
payments_df['PaymentID'] = payments_df['PaymentID'].astype('category')  # Convert PaymentID to category

In [271]:
 payments_df.dtypes

PaymentID            category
RideID                 object
Amount                float64
Mode                   object
PaymentDate    datetime64[ns]
dtype: object

In [272]:
# Output the cleaned dataset's first few rows
payments_cleaned.head()

   PaymentID     RideID  Amount  Mode PaymentDate
0  PAYT11000  RIDE50531   98.86  Card  1986-08-04
1  PAYT11001  RIDE71644   36.48  CASH  1998-02-28
2  PAYT11002  RIDE85572   22.12  CASH  1993/04/17
3  PAYT11003  RIDE57011   42.15  CASH  1993-08-31
4  PAYT11004  RIDE80861    8.36  Cash  1979.09.12

### 4. Cleaning Ride Requests Dataset

In [273]:
# Re-defined check_inconsistencies function
def check_inconsistencies(df):
    inconsistencies = {}

    # Check for invalid date formats
    for column in df.columns:
        if 'date' in column.lower() and df[column].dtype == 'object':  # Date columns
            try:
                pd.to_datetime(df[column], errors='raise')
            except Exception as e:
                inconsistencies[column] = "Invalid date format"
        
        # Check for negative or impossible values in numerical columns
        if df[column].dtype in ['float64', 'int64']:
            if df[column].min() < 0:
                inconsistencies[column] = "Negative values present"
        
        # Check for categorical columns with unexpected values
        if df[column].dtype == 'category':
            unique_values = df[column].unique()
            if len(unique_values) > 10:
                inconsistencies[column] = f"Too many unique values: {unique_values[:5]}"

    return inconsistencies

In [274]:
# Loading ride requests dataset
ride_requests_df = pd.read_csv('C:\\Users\\ayesh\\Desktop\\DWH Assignments\\Dataset\\ride_requests.csv')
print(ride_requests_df)

      RequestID CustomerID RequestedTime  \
0       REQ9000  CUST16216    1979-08-18
1       REQ9001   CUST7724    2025-02-19
2       REQ9002   CUST7807    1976-12-12
3       REQ9003  CUST18158    2015.08.16
4       REQ9004  CUST20001    2008.03.30
...         ...        ...           ...
49995  REQ58995   CUST8391    1977/12/30
49996  REQ58996  CUST18253    2017-01-18
49997  REQ58997  CUST14723    1985-11-30
49998       NaN   CUST8253    1997.01.06
49999  REQ58999   CUST9289    2003/01/02

                                         RequestedPickup  \
0      78585 Burns Fords Apt. 605\nNew Christopher, N...
1               75558 Sloan Dale\nEast Brianna, VA 98039
2      6771 Mcdaniel Inlet Suite 414\nPatriciastad, N...
3                              USNV Gamble\nFPO AA 82547
4      07017 Shannon Junction Apt. 630\nPort Davidbor...
...                                                  ...
49995  9251 Henry Union Apt. 092\nSouth Andrewfort, M...
49996  9422 Parrish Union Suite 221\nAguilarshire, TX...
49997  7600 Lopez Divide Apt. 306\nNew Rebeccaburgh, ...
49998      400 Christine Mill\nNew Charlesport, SC 57015
49999    74426 Scott Highway\nSouth Staceyfort, AL 91602

                                        RequestedDropoff     Status
0      5622 Williams Lakes Apt. 696\nSouth Frank, NH ...  Cancelled
1      90614 Ryan Port Suite 338\nNorth Jessicafurt, ...   accepted
2                 4927 Patel Flats\nWest Aaron, IN 87786  Cancelled
3                 9824 Nancy Wall\nPort Ronald, NY 30882   Accepted
4      4298 Burton Shores Apt. 315\nLake Kathleenland...   accepted
...                                                  ...        ...
49995       106 Perkins Divide\nBrandonborough, NH 49642  Cancelled
49996  000 Davis Motorway Apt. 522\nNew Lorraine, AZ ...  Cancelled
49997                   PSC 6310, Box 3099\nAPO AE 11136  Cancelled
49998         73394 Fields Prairie\nWest Jacob, MD 19285    Pending
49999          6576 Watson Plaza\nNorth Lauren, DE 24113  cancelled

[50000 rows x 6 columns]

In [275]:
# Checking for missing values
ride_requests_missing = ride_requests_df.isnull().sum()
ride_requests_missing

RequestID           1000
CustomerID          2405
RequestedTime       1000
RequestedPickup     1000
RequestedDropoff    1000
Status              1000
dtype: int64

In [276]:
ride_requests_df['RequestedTime'] = ride_requests_df['RequestedTime'].fillna('2023-01-01')  # Fill with a placeholder date (or use latest date)

In [277]:
# Checking for duplicates
ride_requests_duplicates = ride_requests_df.duplicated().sum()
ride_requests_duplicates

0

In [278]:
# Checking for inconsistencies
ride_requests_inconsistencies = check_inconsistencies(ride_requests_df)
ride_requests_inconsistencies

{}

In [279]:
ride_requests_data_types_before = ride_requests_df.dtypes
ride_requests_data_types_before

RequestID           object
CustomerID          object
RequestedTime       object
RequestedPickup     object
RequestedDropoff    object
Status              object
dtype: object

In [280]:
#fixing datatypes
ride_requests_df['RequestedTime'] = pd.to_datetime(ride_requests_df['RequestedTime'], errors='coerce')  # Convert RequestedTime to datetime
ride_requests_df['RequestID'] = ride_requests_df['RequestID'].astype('category')  # Convert RequestID to category

In [281]:
ride_requests_df.dtypes

RequestID                 category
CustomerID                  object
RequestedTime       datetime64[ns]
RequestedPickup             object
RequestedDropoff            object
Status                      object
dtype: object

In [282]:
# For categorical columns, using  mode to fill missing values
ride_requests_df['RequestedPickup'] = ride_requests_df['RequestedPickup'].fillna(ride_requests_df['RequestedPickup'].mode()[0])
ride_requests_df['RequestedDropoff'] = ride_requests_df['RequestedDropoff'].fillna(ride_requests_df['RequestedDropoff'].mode()[0])

In [283]:
# Cleaning the dataset
ride_requests_cleaned = clean_data(ride_requests_df)
ride_requests_cleaned.head()

,RequestID,CustomerID,RequestedTime,RequestedPickup,RequestedDropoff,Status
0,REQ9000,CUST16216,1979-08-18,"78585 Burns Fords Apt. 605\nNew Christopher, N...","5622 Williams Lakes Apt. 696\nSouth Frank, NH ...",Cancelled
1,REQ9001,CUST7724,2025-02-19,"75558 Sloan Dale\nEast Brianna, VA 98039","90614 Ryan Port Suite 338\nNorth Jessicafurt, ...",accepted
2,REQ9002,CUST7807,1976-12-12,"6771 Mcdaniel Inlet Suite 414\nPatriciastad, N...","4927 Patel Flats\nWest Aaron, IN 87786",Cancelled
11,REQ9011,CUST16560,1972-03-22,"48932 Dorothy Forges\nSellerstown, HI 33749",04724 Miller Walks Suite 504\nPort Brittanyvil...,Pending
25,REQ9025,CUST14513,1986-12-23,"40453 Moss Center Suite 417\nSouth Miranda, HI...","126 Timothy Parkways Apt. 096\nWilsonfurt, ND ...",cancelled

In [284]:
# Summary of the cleaned dataset's first few rows
ride_requests_missing, ride_requests_duplicates, ride_requests_inconsistencies

(RequestID           1000
 CustomerID          2405
 RequestedTime       1000
 RequestedPickup     1000
 RequestedDropoff    1000
 Status              1000
 dtype: int64,
 0,
 {})

### 5. Cleaning Vehicles Dataset

In [285]:
# Loading rides dataset
rides_df = pd.read_csv('C:\\Users\\ayesh\\Desktop\\DWH Assignments\\Dataset\\ride_requests.csv')
rides_df

,RequestID,CustomerID,RequestedTime,RequestedPickup,RequestedDropoff,Status
0,REQ9000,CUST16216,1979-08-18,"78585 Burns Fords Apt. 605\nNew Christopher, N...","5622 Williams Lakes Apt. 696\nSouth Frank, NH ...",Cancelled
1,REQ9001,CUST7724,2025-02-19,"75558 Sloan Dale\nEast Brianna, VA 98039","90614 Ryan Port Suite 338\nNorth Jessicafurt, ...",accepted
2,REQ9002,CUST7807,1976-12-12,"6771 Mcdaniel Inlet Suite 414\nPatriciastad, N...","4927 Patel Flats\nWest Aaron, IN 87786",Cancelled
3,REQ9003,CUST18158,2015.08.16,USNV Gamble\nFPO AA 82547,"9824 Nancy Wall\nPort Ronald, NY 30882",Accepted
4,REQ9004,CUST20001,2008.03.30,07017 Shannon Junction Apt. 630\nPort Davidbor...,4298 Burton Shores Apt. 315\nLake Kathleenland...,accepted
...,...,...,...,...,...,...
49995,REQ58995,CUST8391,1977/12/30,"9251 Henry Union Apt. 092\nSouth Andrewfort, M...","106 Perkins Divide\nBrandonborough, NH 49642",Cancelled
49996,REQ58996,CUST18253,2017-01-18,"9422 Parrish Union Suite 221\nAguilarshire, TX...","000 Davis Motorway Apt. 522\nNew Lorraine, AZ ...",Cancelled
49997,REQ58997,CUST14723,1985-11-30,"7600 Lopez Divide Apt. 306\nNew Rebeccaburgh, ...","PSC 6310, Box 3099\nAPO AE 11136",Cancelled
49998,NaN,CUST8253,1997.01.06,"400 Christine Mill\nNew Charlesport, SC 57015","73394 Fields Prairie\nWest Jacob, MD 19285",Pending
49999,REQ58999,CUST9289,2003/01/02,"74426 Scott Highway\nSouth Staceyfort, AL 91602","6576 Watson Plaza\nNorth Lauren, DE 24113",cancelled

In [286]:
# Checking for missing values
rides_missing = rides_df.isnull().sum()
rides_missing

RequestID           1000
CustomerID          2405
RequestedTime       1000
RequestedPickup     1000
RequestedDropoff    1000
Status              1000
dtype: int64

In [287]:
# Checking for duplicates
rides_duplicates = rides_df.duplicated().sum()
rides_duplicates

0

In [288]:
# Checking for inconsistencies
rides_inconsistencies = check_inconsistencies(rides_df)
rides_inconsistencies

{}

In [289]:
# Cleaning the dataset
rides_cleaned = clean_data(rides_df)
rides_cleaned.head()

,RequestID,CustomerID,RequestedTime,RequestedPickup,RequestedDropoff,Status
0,REQ9000,CUST16216,1979-08-18,"78585 Burns Fords Apt. 605\nNew Christopher, N...","5622 Williams Lakes Apt. 696\nSouth Frank, NH ...",Cancelled
1,REQ9001,CUST7724,2025-02-19,"75558 Sloan Dale\nEast Brianna, VA 98039","90614 Ryan Port Suite 338\nNorth Jessicafurt, ...",accepted
2,REQ9002,CUST7807,1976-12-12,"6771 Mcdaniel Inlet Suite 414\nPatriciastad, N...","4927 Patel Flats\nWest Aaron, IN 87786",Cancelled
3,REQ9003,CUST18158,2015.08.16,USNV Gamble\nFPO AA 82547,"9824 Nancy Wall\nPort Ronald, NY 30882",Accepted
4,REQ9004,CUST20001,2008.03.30,07017 Shannon Junction Apt. 630\nPort Davidbor...,4298 Burton Shores Apt. 315\nLake Kathleenland...,accepted

In [290]:
# Summary of missing values, duplicates, and inconsistencies
rides_missing, rides_duplicates, rides_inconsistencies

(RequestID           1000
 CustomerID          2405
 RequestedTime       1000
 RequestedPickup     1000
 RequestedDropoff    1000
 Status              1000
 dtype: int64,
 0,
 {})

### 6. Cleaning Vehicles Dataset

In [291]:
# Loading vehicles dataset
vehicles_df = pd.read_csv('C:\\Users\\ayesh\\Desktop\\DWH Assignments\\Dataset\\vehicles.csv')
vehicles_df

     VehicleID PlateNumber       Type  Capacity AssignedDriverID
0      VEH2000     6054 QL      Sedan       3.0          DRV3864
1      VEH2001     055-HFP      Sedan       4.0          DRV3841
2      VEH2002     762 ZBX  Hatchback       6.0          DRV1973
3      VEH2003     M88 7AI      sedan       6.0          DRV3920
4      VEH2004     23OC983        SUV       6.0          DRV2621
...        ...         ...        ...       ...              ...
2995   VEH4995     473-HHI        SUV       4.0          DRV2700
2996   VEH4996       405H8        Van       3.0          DRV1508
2997   VEH4997     TQB 174        SUV       5.0          DRV4653
2998   VEH4998     079 OOJ        SUV       6.0          DRV5162
2999   VEH4999     QRQ 295      Sedan       3.0          DRV2654

[3000 rows x 5 columns]

In [292]:
vehicles_df.dtypes

VehicleID            object
PlateNumber          object
Type                 object
Capacity            float64
AssignedDriverID     object
dtype: object

In [293]:
# Define the categories for the 'VehicleID' column
vehicles_df['VehicleID'] = vehicles_df['VehicleID'].astype('category')
vehicles_df['VehicleID'] = vehicles_df['VehicleID'].cat.add_categories(['Unknown_VehicleID'])

# Filling missing VehicleID with a default placeholder value
vehicles_df['VehicleID'] = vehicles_df['VehicleID'].fillna('Unknown_VehicleID')

# Filling missing Type with a default value (e.g., 'Unknown')
vehicles_df['Type'] = vehicles_df['Type'].fillna('Unknown_Type')

# Filling missing AssignedDriverID with a default value (e.g., 'Unknown_DriverID')
vehicles_df['AssignedDriverID'] = vehicles_df['AssignedDriverID'].fillna('Unknown_DriverID')

# Checking for any remaining missing values after filling
vehicles_missing_after_final = vehicles_df.isnull().sum()
vehicles_missing_after_final

VehicleID            0
PlateNumber         60
Type                 0
Capacity            60
AssignedDriverID     0
dtype: int64

In [294]:
vehicles_data_types_after_final = vehicles_df.dtypes
vehicles_data_types_after_final

VehicleID           category
PlateNumber           object
Type                  object
Capacity             float64
AssignedDriverID      object
dtype: object

In [295]:
# Checking for duplicates
vehicles_duplicates = vehicles_df.duplicated().sum()
vehicles_duplicates

0

In [296]:
# Checking for inconsistencies
vehicles_inconsistencies = check_inconsistencies(vehicles_df)
vehicles_inconsistencies

{'VehicleID': "Too many unique values: ['VEH2000', 'VEH2001', 'VEH2002', 'VEH2003', 'VEH2004']\nCategories (2941, object): ['VEH2000', 'VEH2001', 'VEH2002', 'VEH2003', ..., 'VEH4997', 'VEH4998', 'VEH4999', 'Unknown_VehicleID']"}

In [297]:
# Cleaning the dataset
vehicles_cleaned = clean_data(vehicles_df)
vehicles_cleaned.head()

  VehicleID PlateNumber       Type  Capacity AssignedDriverID
0   VEH2000     6054 QL      Sedan       3.0          DRV3864
1   VEH2001     055-HFP      Sedan       4.0          DRV3841
2   VEH2002     762 ZBX  Hatchback       6.0          DRV1973
3   VEH2003     M88 7AI      sedan       6.0          DRV3920
4   VEH2004     23OC983        SUV       6.0          DRV2621

In [298]:
# Summary of missing values, duplicates, and inconsistencies
vehicles_missing, vehicles_duplicates, vehicles_inconsistencies

(VehicleID            60
 PlateNumber          60
 Type                 60
 Capacity             60
 AssignedDriverID    139
 dtype: int64,
 0,
 {'VehicleID': "Too many unique values: ['VEH2000', 'VEH2001', 'VEH2002', 'VEH2003', 'VEH2004']\nCategories (2941, object): ['VEH2000', 'VEH2001', 'VEH2002', 'VEH2003', ..., 'VEH4997', 'VEH4998', 'VEH4999', 'Unknown_VehicleID']"})

In [299]:
remaining_missing_values = {
    'Customers Missing Values': customers_cleaned.isnull().sum(),
    'Payments Missing Values': payments_cleaned.isnull().sum(),
    'Ride Requests Missing Values': ride_requests_cleaned.isnull().sum(),
    'Rides Missing Values': rides_cleaned.isnull().sum(),
}

# Displaying the remaining missing values after filling
remaining_missing_values

{'Customers Missing Values': CustomerID    0
 FullName      0
 Phone         0
 SignupDate    0
 Email         0
 dtype: int64,
 'Payments Missing Values': PaymentID      0
 RideID         0
 Amount         0
 Mode           0
 PaymentDate    0
 dtype: int64,
 'Ride Requests Missing Values': RequestID           0
 CustomerID          0
 RequestedTime       0
 RequestedPickup     0
 RequestedDropoff    0
 Status              0
 dtype: int64,
 'Rides Missing Values': RequestID           0
 CustomerID          0
 RequestedTime       0
 RequestedPickup     0
 RequestedDropoff    0
 Status              0
 dtype: int64}